# Generated by Django 6.0.5 on 2026-05-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 — Direct combustion'), ('scope2', 'Scope 2 — Purchased electricity'), ('scope3', 'Scope 3 — Value chain / travel')], max_length=10)),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('electricity', 'Electricity'), ('flight', 'Flight'), ('hotel', 'Hotel'), ('ground_transport', 'Ground Transport')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_normalized', models.CharField(max_length=20)),
                ('original_quantity', models.CharField(max_length=100)),
                ('original_unit', models.CharField(max_length=50)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('site_code', models.CharField(blank=True, max_length=100)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('supplier_vendor', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Record created'), ('approved', 'Record approved'), ('rejected', 'Record rejected'), ('flagged', 'Record flagged'), ('note_added', 'Note added')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='ingestion.emissionrecord')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('parsed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.ingestionbatch'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionbatch')),
            ],
            options={
                'unique_together': {('batch', 'row_index')},
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.tenant'),
        ),
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('missing_field', 'Missing required field'), ('unknown_unit', 'Unrecognized unit'), ('outlier', 'Statistical outlier (>3σ from mean)'), ('unknown_site', 'Unknown site/plant code'), ('date_parse_error', 'Date parse error'), ('negative_value', 'Negative quantity')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='ingestion.emissionrecord')),
            ],
        ),
    ]
